export const initalPlayers = [
  {
    name: "Marcos",
    color: "#ff0000",
    bgColor: "rgb(255, 0, 0, 0.5)",
    as: null,
    duque: null,
    terno: null,
    quadra: null,
    quina: null,
    sena: null,
    full: null,
    seguida: null,
    quadrada: null,
    general: null,
  },
  {
    name: "Faria",
    color: "#0000ff",
    bgColor: "rgb(0, 0, 255, 0.5)",
    as: null,
    duque: null,
    terno: null,
    quadra: null,
    quina: null,
    sena: null,
    full: null,
    seguida: null,
    quadrada: null,
    general: null,
  },
  {
    name: "Emanuel",
    as: null,
    color: "#00ff00",
    bgColor: "rgb(0, 255, 0,0.5)",
    duque: null,
    terno: null,
    quadra: null,
    quina: null,
    sena: null,
    full: null,
    seguida: null,
    quadrada: null,
    general: null,
  },
  {
    name: "João Lucas",
    color: "#ffa500",
    bgColor: "rgb(255, 165, 0,0.5)",
    as: null,
    duque: null,
    terno: null,
    quadra: null,
    quina: null,
    sena: null,
    full: null,
    seguida: null,
    quadrada: null,
    general: null,
  },
];
